services:
  web:
    build: .
    container_name: classifier-demo
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgresql://postgres:password@postgres:5432/classifier_db
      PYTHONPATH: /app
    depends_on:
      - postgres

  postgres:
    image: postgres:18
    container_name: classifier-postgres-demo
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: classifier_db
    ports:
      - "5432:5432"
    volumes:
      - classifier-postgres-data:/var/lib/postgresql/
      - ./src/sql/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./src/sql/db_seed.sql:/docker-entrypoint-initdb.d/2-db_seed.sql

volumes:
  classifier-postgres-data: