services:
  web:
    build: .
    container_name: classifier-demo
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgresql://postgres:password@postgres:5432/classifier_db
      PYTHONPATH: /app
      MLFLOW_TRACKING: http://mlflow:5000
    depends_on:
      - postgres
      - mlflow

  postgres:
    image: postgres:18
    container_name: classifier-postgres-demo
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: classifier_db
    ports:
      - "5432:5432"
    volumes:
      - classifier-postgres-data:/var/lib/postgresql/
      - ./src/sql/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./src/sql/db_seed.sql:/docker-entrypoint-initdb.d/2-db_seed.sql
  
  mlflow:
    image: ghcr.io/mlflow/mlflow:v3.1.1
    container_name: classifier-mlflow
    ports:
      - "5001:5000"
    volumes:
      - mlflow-data:/mlflow
    command: >
      mlflow server
      --host 0.0.0.0
      --port 5000
      --backend-store-uri sqlite:////mlflow/mlflow.db
      --default-artifact-root /mlflow/artifacts

volumes:
  classifier-postgres-data:
  mlflow-data: